# Render Blueprint for Bookbee backend
# Dokumentation: https://render.com/docs/infrastructure-as-code

services:
  - type: web
    name: bookbee-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    # Schema operationer køres nu lokalt - serveren starter direkte uden migration
    # For at deploye schema: kør lokalt `npm run deploy:schema` før deployment
    startCommand: >-
      sh -c 'echo Starting backend without migration; echo DBLEN=$(echo -n "$DATABASE_URL" | wc -c); node dist/index.js'
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 4000
      - key: ALLOWED_ORIGINS
        value: http://localhost:3000,https://bookbee-flame.vercel.app
      - key: DATABASE_URL
        sync: false  # Pooled connection (port 6543) - bruges til runtime
      - key: DIRECT_URL
        sync: false  # Direct connection (port 5432) - bruges til migrations (kun lokalt)
