# Render Blueprint for Bookbee backend
# Dokumentation: https://render.com/docs/infrastructure-as-code

services:
  - type: web
    name: bookbee-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    # Midlertidig debug startCommand: printer DB længde, forsøger migrate status først.
    # Når alt virker: skift tilbage til: npx prisma migrate deploy && node dist/index.js
    startCommand: >-
      sh -c 'echo Using pooled DB; echo DBLEN=$(echo -n "$DATABASE_URL" | wc -c); npx prisma migrate deploy || echo "(warning) migrate failed - continuing"; node dist/index.js'
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 4000
      - key: ALLOWED_ORIGINS
        value: http://localhost:3000
      - key: DATABASE_URL
        sync: false  # Sættes manuelt i Render dashboardet (Supabase connection string)
      - key: DATABASE_URL_POOLED
        sync: false  # (Valgfri) Supabase pgBouncer pooled connection string – kan bruges i stedet for DATABASE_URL hvis direkte host fejler
      - key: DIRECT_URL
        sync: false  # Direkte (5432) forbindelse til migrering, hvis DATABASE_URL er sat til pooled (6543)
